#!/bin/bash

# start cron first
/usr/sbin/cron

# initialize commands
/usr/local/bin/init-cmds

# block forever
sleep infinity

# add event handler for quicker shutdown
trap 'exit 0' SIGTERM

# block forever
read forever
