#!/bin/bash

# start cron first
/usr/sbin/cron

# initialize commands
/usr/local/bin/init-cmds

# add event handler for quicker shutdown
trap 'exit 0' SIGTERM

# block forever
touch /tmp/forever
tail -f /tmp/forever
